# Things to do in this Dockerfile, which will run the toHtml example:
#
#   + get new apt stuff:
#     apt update
#     apt install -y apt-transport-https
#   + add to /etc/apt/sources.list:
#     deb https://cloud.r-project.org/bin/linux/ubuntu xenial/
#   + add ubuntu apt key:
#     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9
#     apt update
#   + install system packages:
#     apt install libxml2-utils xsltproc r-base libxml2-dev \
#         libcurl4-openssl-dev libssl-dev
